### ISSUE TITLE
Update slides link

### ISSUE THREAD

**Issue by JulieKuehl** [wptrainingteam/introduction-to-css#19]
The link to the slides is a 404. Please update the URL to the new location (if needed).

**Comment by jessecowens** [comment]
@carlotrimarchi

**Comment by megane9988** [comment]
I think this issue solved by these pull requests

https://github.com/wptrainingteam/introduction-to-css/pull/22/files
https://github.com/wptrainingteam/introduction-to-css/pull/21/files

@JulieKuehl 
@jessecowens 
@carlotrimarchi

**Comment by JulieKuehl** [comment]
I believe that you are right @megane9988. I've pulled the dev branch into the master branch and it should be all good. Thanks for pointing that out!
